### ISSUE TITLE
mesos-cli run error

### ISSUE THREAD

**Issue by GoodHaHa** [vektorlab/mesos-cli#4]
Hill Kevin, 
When I execute the `mesos-cli task --shell 'echo $(date); sleep 2' | mesos-cli run --restart -
`，but I get this mistake:

```shell
root@sunwuhao:~# mesos-cli task --shell 'echo $(date); sleep 2' | mesos-cli run -
2017-03-29T18:47:46.207+0800	INFO	CALL	{"type": "SUBSCRIBE", "framework": "&FrameworkInfo{User:root,Name:mesos-cli,ID:&FrameworkID{Value:,},FailoverTimeout:nil,Checkpoint:nil,Role:nil,Hostname:nil,Principal:nil,WebuiUrl:nil,Capabilities:[],Labels:nil,}"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x9d1e68]

goroutine 7 [running]:
github.com/vektorlab/mesos-cli/runner.LogEvent(0xc4203b00f0, 0xc4202f4060)
	/home/kevin/repos/go/src/github.com/vektorlab/mesos-cli/runner/helpers.go:24 +0x668
github.com/vektorlab/mesos-cli/runner.handler.func1.1(0xc4203b00f0, 0x0, 0x0)
	/home/kevin/repos/go/src/github.com/vektorlab/mesos-cli/runner/runner.go:127 +0x58
github.com/vektorlab/mesos-cli/vendor/github.com/mesos/mesos-go/scheduler/events.HandlerFunc.HandleEvent(0xc4202d4b20, 0xc4203b00f0, 0xc4203b00f0, 0x0)
	/home/kevin/repos/go/src/github.com/vektorlab/mesos-cli/vendor/github.com/mesos/mesos-go/scheduler/events/events.go:39 +0x30
github.com/vektorlab/mesos-cli/vendor/github.com/mesos/mesos-go/extras/scheduler/controller.eventLoop(0xdd7b60, 0xc42023b040, 0xc42022f000, 0xdd40a0, 0xc4202d4a40, 0xdd40e0, 0xc4202d4b20, 0xc4202d7560, 0xc4203a4080, 0x0, ...)
	/home/kevin/repos/go/src/github.com/vektorlab/mesos-cli/vendor/github.com/mesos/mesos-go/extras/scheduler/controller/controller.go:111 +0x129
github.com/vektorlab/mesos-cli/vendor/github.com/mesos/mesos-go/extras/scheduler/controller.processSubscription(0xdd7b60, 0xc42023b040, 0xc42022f000, 0xdd40a0, 0xc4202d4a40, 0xdd40e0, 0xc4202d4b20, 0xc4202d7560, 0xdd5e20, 0xc4203aa080, ...)
	/home/kevin/repos/go/src/github.com/vektorlab/mesos-cli/vendor/github.com/mesos/mesos-go/extras/scheduler/controller/controller.go:96 +0xb7
github.com/vektorlab/mesos-cli/vendor/github.com/mesos/mesos-go/extras/scheduler/controller.(*controllerImpl).Run(0xc4202b90b8, 0xdd7b60, 0xc42023b040, 0xc42022f000, 0xdd40a0, 0xc4202d4a40, 0xdd40e0, 0xc4202d4b20, 0xc4202d7560, 0x0, ...)
	/home/kevin/repos/go/src/github.com/vektorlab/mesos-cli/vendor/github.com/mesos/mesos-go/extras/scheduler/controller/controller.go:85 +0x25c
github.com/vektorlab/mesos-cli/runner.Run.func1(0xc4202b90d0, 0xc4202b90c0, 0xdd2760, 0xc4202b90b8, 0xdd7b60, 0xc42023b040, 0xc42022f000, 0xdd40a0, 0xc4202d4a40, 0xdd40e0, ...)
	/home/kevin/repos/go/src/github.com/vektorlab/mesos-cli/runner/runner.go:157 +0x99
created by github.com/vektorlab/mesos-cli/runner.Run
	/home/kevin/repos/go/src/github.com/vektorlab/mesos-cli/runner/runner.go:170 +0x506
```

**Comment by kevinschoon** [comment]
Hi -- 

I have released [v0.0.8](https://github.com/vektorlab/mesos-cli/releases/tag/v0.0.8) which I believe should fix this issue. Give that version a try. 

Also please let me know what version of Mesos you are running.

Thank you!

**Comment by kevinschoon** [comment]
From within the source directory of mesos-cli you should now be able to just type `mesos run` and it should demonstrate using the new TaskGroup functionality: https://github.com/vektorlab/mesos-cli/blob/master/Mesosfile if you want to give that a shot.

Kevin

**Comment by GoodHaHa** [comment]
HIll, kevin 
Thinks a lot,I running mesos with version 1.0.2.

**Comment by GoodHaHa** [comment]
Hill, kevin

now I get this info:

```
[root@mesos-master-dev062-cqdx ~]# mesos-cli run
2017-04-05T14:52:07.100+0800	INFO	CALL	{"type": "SUBSCRIBE", "framework": "&FrameworkInfo{User:root,Name:mesos-cli,ID:&FrameworkID{Value:,},FailoverTimeout:nil,Checkpoint:nil,Role:nil,Hostname:nil,Principal:nil,WebuiUrl:nil,Capabilities:[],Labels:nil,Roles:[],}"}
2017-04-05T14:52:07.105+0800	WARN	scheduler	{"error": "Post http://localhost:5050/api/v1/scheduler: dial tcp 0.0.0.0:0->127.0.0.1:5050: getsockopt: connection refused"}
```
and

```
[root@mesos-master-dev062-cqdx ~]# mesos-cli run --master="http://mesos-master-dev062-cqdx.qiyi.virtual:5050/#/" 
2017-04-05T14:51:25.212+0800	INFO	CALL	{"type": "SUBSCRIBE", "framework": "&FrameworkInfo{User:root,Name:mesos-cli,ID:&FrameworkID{Value:,},FailoverTimeout:nil,Checkpoint:nil,Role:nil,Hostname:nil,Principal:nil,WebuiUrl:nil,Capabilities:[],Labels:nil,Roles:[],}"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xa1b07d]

goroutine 7 [running]:
github.com/vektorlab/mesos-cli/runner.LogEvent(0xc42039e0f0, 0xc4202d6060)
	/home/kevin/repos/go/src/github.com/vektorlab/mesos-cli/runner/helpers.go:25 +0x3ad
github.com/vektorlab/mesos-cli/runner.handler.func1.1(0xc42039e0f0, 0x0, 0x0)
	/home/kevin/repos/go/src/github.com/vektorlab/mesos-cli/runner/runner.go:135 +0x58
github.com/vektorlab/mesos-cli/vendor/github.com/mesos/mesos-go/scheduler/events.HandlerFunc.HandleEvent(0xc4202caee0, 0xc42039e0f0, 0xc42039e0f0, 0x0)
	/home/kevin/repos/go/src/github.com/vektorlab/mesos-cli/vendor/github.com/mesos/mesos-go/scheduler/events/events.go:39 +0x30
github.com/vektorlab/mesos-cli/vendor/github.com/mesos/mesos-go/extras/scheduler/controller.eventLoop(0xe4bd80, 0xc4202493b0, 0xc4201ac6c0, 0xe482c0, 0xc4202cae00, 0xe48300, 0xc4202caee0, 0xc4202cd140, 0xc420392080, 0x0, ...)
	/home/kevin/repos/go/src/github.com/vektorlab/mesos-cli/vendor/github.com/mesos/mesos-go/extras/scheduler/controller/controller.go:111 +0x129
github.com/vektorlab/mesos-cli/vendor/github.com/mesos/mesos-go/extras/scheduler/controller.processSubscription(0xe4bd80, 0xc4202493b0, 0xc4201ac6c0, 0xe482c0, 0xc4202cae00, 0xe48300, 0xc4202caee0, 0xc4202cd140, 0xe4a040, 0xc420398080, ...)
	/home/kevin/repos/go/src/github.com/vektorlab/mesos-cli/vendor/github.com/mesos/mesos-go/extras/scheduler/controller/controller.go:96 +0xb7
github.com/vektorlab/mesos-cli/vendor/github.com/mesos/mesos-go/extras/scheduler/controller.(*controllerImpl).Run(0xc4202c9400, 0xe4bd80, 0xc4202493b0, 0xc4201ac6c0, 0xe482c0, 0xc4202cae00, 0xe48300, 0xc4202caee0, 0xc4202cd140, 0x0, ...)
	/home/kevin/repos/go/src/github.com/vektorlab/mesos-cli/vendor/github.com/mesos/mesos-go/extras/scheduler/controller/controller.go:85 +0x25c
github.com/vektorlab/mesos-cli/runner.Run.func1(0xc4202c93a0, 0xc4202c9390, 0xe469c0, 0xc4202c9400, 0xe4bd80, 0xc4202493b0, 0xc4201ac6c0, 0xe482c0, 0xc4202cae00, 0xe48300, ...)
	/home/kevin/repos/go/src/github.com/vektorlab/mesos-cli/runner/runner.go:164 +0x99
created by github.com/vektorlab/mesos-cli/runner.Run
	/home/kevin/repos/go/src/github.com/vektorlab/mesos-cli/runner/runner.go:177 +0x531
```

There is an other question, how to use the local  command?
when I running ./mesos-cli local status ,I get :

```
[root@mesos-master-dev001-bjdx ~]# ./mesos-cli local status 
Encountered Error: Error response from daemon: client is newer than server (client API version: 1.26, server API version: 1.24)
```
Thank you very much.

**Comment by kevinschoon** [comment]
Hi -- 

The first error you posted is expected. mesos-cli will attempt to make a connection to localhost:5050 by default. You can modify this behavior by editing the default config file: `~/.mesos-cli.json`.

Regarding the exception: mesos-cli has been developed only against versions `1.1.0` and `1.2.0` of Mesos. There was a [fix](https://issues.apache.org/jira/browse/MESOS-6497) for a similar issue implemented for this. If possible, upgrading Mesos to one of the two versions I mention will fix the issue. I will try to target compatibility back to Mesos version `1.0.0` in the next week.

Unfortunately it looks like the `local` command is failing because you are running an older version of Docker. If you upgrade to docker `1.13.1` it should resolve the issue. I will implement a fix for this in the next week (there is no good reason for requiring such a new version of Docker).

Thanks!

**Comment by GoodHaHa** [comment]
Hill, kevin 
Thank you for your answer, I will continuous attention.

**Comment by kevinschoon** [comment]
@GoodHaHa Sorry for the long delay. I have decided to remove the `mesos local` functionality as I feel it is too broad for this tool. We maintain a [Docker image](https://github.com/vektorcloud/mesos) that makes it easy to get a local cluster running for dev/testing. 

Thanks!
